spring:
  application:
    name: tcpserver
server:
  port: 8087
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
app:
  socket:
    port: 9091
  poolconfig:
    coresize: 2
    maxsize: 10
