package com.corunet.marioapp.libraries.tcpclient.service.impl;

import java.nio.charset.Charset;
import java.util.Random;

import org.springframework.stereotype.Service;

import com.corunet.marioapp.libraries.tcpclient.service.IMessageService;

import lombok.extern.log4j.Log4j2;

@Service
@Log4j2
public class MessageService implements IMessageService {
	
	@Override
	public String getMessage() {
		log.info("Iniciando la formacion del mensaje de envio");
		StringBuilder message = new StringBuilder();
		int randomValue = new Random().nextInt(3) + 1;
		message.append("0");
		message.append(String.valueOf(randomValue));
		message.append("IP10.1.6.");
		randomValue = new Random().nextInt(254) + 1;
		message.append(String.valueOf(randomValue));
		byte[] array = new byte[5];
		new Random().nextBytes(array);
		message.append("HOSTP").append(new String(array, Charset.forName("UTF-8")));
		message.append("DESCRIPCIONAUTOGENERATEDTRIALDESCRIPTION");
		log.info("Mensaje formado: {}", message.toString());
		return message.toString();
	}

}
